[0m15:27:09.895265 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1092daad0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1092ee4d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1092eeed0>]}


============================== 15:27:09.897830 | ab4d5bf7-57e4-48a6-bd23-ef5c6a8cd180 ==============================
[0m15:27:09.897830 [info ] [MainThread]: Running with dbt=1.9.0
[0m15:27:09.898125 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/Users/andrewspruce/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt init expectations', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:27:09.905097 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'PosixPath'.. Dictionary: {'dir': PosixPath('/Users/andrewspruce/.dbt')}
[0m15:27:09.905317 [info ] [MainThread]: Creating dbt configuration folder at 
[0m15:27:09.906247 [debug] [MainThread]: Starter project path: /Users/andrewspruce/Code/Expectations/.venv/lib/python3.11/site-packages/dbt/include/starter_project
[0m15:27:09.910050 [info ] [MainThread]: 
Your new dbt project "expectations" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m15:27:09.910250 [info ] [MainThread]: Setting up your profile.
[0m15:27:14.206921 [info ] [MainThread]: Profile expectations written to /Users/andrewspruce/.dbt/profiles.yml using target's sample configuration. Once updated, you'll be able to start developing with dbt.
[0m15:27:14.212676 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 4.350842, "process_in_blocks": "0", "process_kernel_time": 0.147446, "process_mem_max_rss": "114278400", "process_out_blocks": "0", "process_user_time": 0.65554}
[0m15:27:14.213010 [debug] [MainThread]: Command `dbt init` succeeded at 15:27:14.212953 after 4.35 seconds
[0m15:27:14.213215 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10927f650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1092ee610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1092eded0>]}
[0m15:27:14.213421 [debug] [MainThread]: Flushing usage events
[0m15:27:14.558000 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:32:55.264489 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1112cfa10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1112dda50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1112de710>]}


============================== 11:32:55.267247 | bd64ac37-de5d-44f8-9503-2fcd07de1af4 ==============================
[0m11:32:55.267247 [info ] [MainThread]: Running with dbt=1.9.0
[0m11:32:55.267539 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/Users/andrewspruce/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m11:32:55.267825 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/andrewspruce/Code/Expectations/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:32:55.276185 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.047089834, "process_in_blocks": "0", "process_kernel_time": 0.127611, "process_mem_max_rss": "96026624", "process_out_blocks": "0", "process_user_time": 0.524685}
[0m11:32:55.276524 [debug] [MainThread]: Command `dbt run` failed at 11:32:55.276469 after 0.05 seconds
[0m11:32:55.276929 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1112cef50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104915b10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111274e90>]}
[0m11:32:55.277265 [debug] [MainThread]: Flushing usage events
[0m11:32:55.782793 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:37:02.897860 [debug] [ScriptRunn]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x12820cc90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1282747d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1282b5510>]}


============================== 12:37:02.900828 | 7c130781-be2d-4aa5-bbf7-adf4246dc54b ==============================
[0m12:37:02.900828 [info ] [ScriptRunn]: Running with dbt=1.9.0
[0m12:37:02.901162 [debug] [ScriptRunn]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/andrewspruce/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt ', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:37:02.901472 [error] [ScriptRunn]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/andrewspruce/Code/Expectations/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:37:02.917869 [debug] [ScriptRunn]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.07522125, "process_in_blocks": "0", "process_kernel_time": 1.24312, "process_mem_max_rss": "153780224", "process_out_blocks": "0", "process_user_time": 7.417268}
[0m12:37:02.918335 [debug] [ScriptRunn]: Command `cli run` failed at 12:37:02.918281 after 0.08 seconds
[0m12:37:02.918559 [debug] [ScriptRunn]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x128291e90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x12822d010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x12820af10>]}
[0m12:37:02.918797 [debug] [ScriptRunn]: Flushing usage events
[0m12:37:03.251201 [debug] [ScriptRunn]: An error was encountered while trying to flush usage events
[0m12:40:24.926751 [debug] [ScriptRunn]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10d610e10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10d612590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10d49ba50>]}


============================== 12:40:24.927414 | ccdca354-d5e9-48a1-a5ab-eafe62ead7d7 ==============================
[0m12:40:24.927414 [info ] [ScriptRunn]: Running with dbt=1.9.0
[0m12:40:24.927798 [debug] [ScriptRunn]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/andrewspruce/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt ', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:40:24.928093 [error] [ScriptRunn]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/andrewspruce/Code/Expectations/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:40:24.928368 [debug] [ScriptRunn]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.002639667, "process_in_blocks": "0", "process_kernel_time": 1.307148, "process_mem_max_rss": "155516928", "process_out_blocks": "0", "process_user_time": 7.746524}
[0m12:40:24.928625 [debug] [ScriptRunn]: Command `cli run` failed at 12:40:24.928578 after 0.00 seconds
[0m12:40:24.928806 [debug] [ScriptRunn]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10d49ba50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x128299750>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x128299690>]}
[0m12:40:24.928994 [debug] [ScriptRunn]: Flushing usage events
[0m12:40:25.258768 [debug] [ScriptRunn]: An error was encountered while trying to flush usage events
[0m12:50:11.144149 [debug] [ScriptRunn]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1197deb50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11dd21e50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105a6f4d0>]}


============================== 12:50:11.146945 | badf0231-6e18-4640-b9ca-9300194c3519 ==============================
[0m12:50:11.146945 [info ] [ScriptRunn]: Running with dbt=1.9.0
[0m12:50:11.147736 [debug] [ScriptRunn]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/Users/andrewspruce/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt ', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:50:11.148077 [error] [ScriptRunn]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/andrewspruce/Code/Expectations/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:50:11.149809 [debug] [ScriptRunn]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.05345404, "process_in_blocks": "0", "process_kernel_time": 0.258322, "process_mem_max_rss": "179666944", "process_out_blocks": "0", "process_user_time": 1.026493}
[0m12:50:11.150316 [debug] [ScriptRunn]: Command `cli run` failed at 12:50:11.150259 after 0.05 seconds
[0m12:50:11.150535 [debug] [ScriptRunn]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11dcc8c50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11dcc51d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11dcd9450>]}
[0m12:50:11.150754 [debug] [ScriptRunn]: Flushing usage events
[0m12:50:11.484915 [debug] [ScriptRunn]: An error was encountered while trying to flush usage events
[0m12:53:24.738741 [debug] [ScriptRunn]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11dd96bd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106f74690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1197d1690>]}


============================== 12:53:24.739622 | 80a4b952-443a-4e34-bfe3-239b12742c47 ==============================
[0m12:53:24.739622 [info ] [ScriptRunn]: Running with dbt=1.9.0
[0m12:53:24.740218 [debug] [ScriptRunn]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/Users/andrewspruce/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt ', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:53:24.740730 [error] [ScriptRunn]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/andrewspruce/Code/Expectations/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:53:24.741223 [debug] [ScriptRunn]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.004746917, "process_in_blocks": "0", "process_kernel_time": 0.371019, "process_mem_max_rss": "182681600", "process_out_blocks": "0", "process_user_time": 1.973087}
[0m12:53:24.741721 [debug] [ScriptRunn]: Command `cli run` failed at 12:53:24.741630 after 0.01 seconds
[0m12:53:24.742089 [debug] [ScriptRunn]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11dcaa390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106f8b4d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11dcc9750>]}
[0m12:53:24.742437 [debug] [ScriptRunn]: Flushing usage events
[0m12:53:25.073454 [debug] [ScriptRunn]: An error was encountered while trying to flush usage events
[0m13:04:25.871102 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1074cf810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1074e6c10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1074e7610>]}


============================== 13:04:25.873666 | fd5b6e15-af0a-4a73-a989-93b3a89ec2f2 ==============================
[0m13:04:25.873666 [info ] [MainThread]: Running with dbt=1.9.0
[0m13:04:25.873955 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/andrewspruce/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m13:04:25.874246 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/andrewspruce/Code/Expectations/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:04:25.875132 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.034333415, "process_in_blocks": "0", "process_kernel_time": 0.097865, "process_mem_max_rss": "95813632", "process_out_blocks": "0", "process_user_time": 0.512148}
[0m13:04:25.875397 [debug] [MainThread]: Command `dbt run` failed at 13:04:25.875351 after 0.03 seconds
[0m13:04:25.875569 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1025d8350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1074e6910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1074e7590>]}
[0m13:04:25.875729 [debug] [MainThread]: Flushing usage events
[0m13:04:26.208772 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:10:23.105393 [debug] [ScriptRunn]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11f7bef90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1049c79d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11f815610>]}


============================== 13:10:23.108147 | 2a8bce2b-b11a-4227-9635-c69cbc3860ac ==============================
[0m13:10:23.108147 [info ] [ScriptRunn]: Running with dbt=1.9.0
[0m13:10:23.108516 [debug] [ScriptRunn]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/Users/andrewspruce/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt ', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:10:23.108870 [error] [ScriptRunn]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/andrewspruce/Code/Expectations/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:10:23.110945 [debug] [ScriptRunn]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.051412668, "process_in_blocks": "0", "process_kernel_time": 0.250801, "process_mem_max_rss": "180912128", "process_out_blocks": "0", "process_user_time": 1.090147}
[0m13:10:23.111437 [debug] [ScriptRunn]: Command `cli run` failed at 13:10:23.111350 after 0.05 seconds
[0m13:10:23.111724 [debug] [ScriptRunn]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11f704650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11f6ff310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11f817a90>]}
[0m13:10:23.111961 [debug] [ScriptRunn]: Flushing usage events
[0m13:10:24.483184 [debug] [ScriptRunn]: An error was encountered while trying to flush usage events
[0m14:01:47.988868 [debug] [ScriptRunn]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11f704c90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11f0a11d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11bc42b10>]}


============================== 14:01:47.989670 | 0bfd91f9-a994-40d4-8db8-db00cebf13c8 ==============================
[0m14:01:47.989670 [info ] [ScriptRunn]: Running with dbt=1.9.0
[0m14:01:47.990172 [debug] [ScriptRunn]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/Users/andrewspruce/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt ', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:01:47.990640 [error] [ScriptRunn]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/andrewspruce/Code/Expectations/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:01:47.991224 [debug] [ScriptRunn]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.005906167, "process_in_blocks": "0", "process_kernel_time": 0.590281, "process_mem_max_rss": "183238656", "process_out_blocks": "0", "process_user_time": 3.611946}
[0m14:01:47.991638 [debug] [ScriptRunn]: Command `cli run` failed at 14:01:47.991558 after 0.01 seconds
[0m14:01:47.991922 [debug] [ScriptRunn]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11f816c50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11f8142d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11f8165d0>]}
[0m14:01:47.992221 [debug] [ScriptRunn]: Flushing usage events
[0m14:01:48.329283 [debug] [ScriptRunn]: An error was encountered while trying to flush usage events
[0m14:06:07.455902 [debug] [ScriptRunn]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11ba00390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11b9d95d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11ba7bd50>]}


============================== 14:06:07.459219 | 59899838-2bdf-4d8b-8d67-55084c68624f ==============================
[0m14:06:07.459219 [info ] [ScriptRunn]: Running with dbt=1.9.0
[0m14:06:07.459690 [debug] [ScriptRunn]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/Users/andrewspruce/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt ', 'send_anonymous_usage_stats': 'True'}
[0m14:06:07.460081 [error] [ScriptRunn]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/andrewspruce/Code/Expectations/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:06:07.462160 [debug] [ScriptRunn]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.057490334, "process_in_blocks": "0", "process_kernel_time": 0.329417, "process_mem_max_rss": "180666368", "process_out_blocks": "0", "process_user_time": 2.024824}
[0m14:06:07.462593 [debug] [ScriptRunn]: Command `cli run` failed at 14:06:07.462531 after 0.06 seconds
[0m14:06:07.462860 [debug] [ScriptRunn]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x119884950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11ba24a50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11b9e17d0>]}
[0m14:06:07.463089 [debug] [ScriptRunn]: Flushing usage events
[0m14:06:07.798471 [debug] [ScriptRunn]: An error was encountered while trying to flush usage events
[0m14:08:32.901013 [debug] [ScriptRunn]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x119dc0990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x119e7cad0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x119e7d590>]}


============================== 14:08:32.903375 | 982c4c70-3ea0-4c10-9f9e-56ed4321ab38 ==============================
[0m14:08:32.903375 [info ] [ScriptRunn]: Running with dbt=1.9.0
[0m14:08:32.903838 [debug] [ScriptRunn]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/andrewspruce/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt ', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:08:32.904194 [error] [ScriptRunn]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/andrewspruce/Code/Expectations/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:08:32.905460 [debug] [ScriptRunn]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.04465404, "process_in_blocks": "0", "process_kernel_time": 0.266432, "process_mem_max_rss": "180207616", "process_out_blocks": "0", "process_user_time": 1.38278}
[0m14:08:32.905753 [debug] [ScriptRunn]: Command `cli run` failed at 14:08:32.905704 after 0.04 seconds
[0m14:08:32.905967 [debug] [ScriptRunn]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x119e45dd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x119ddd710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x119dc2bd0>]}
[0m14:08:32.906148 [debug] [ScriptRunn]: Flushing usage events
[0m14:08:33.236642 [debug] [ScriptRunn]: An error was encountered while trying to flush usage events
